"""
RNS Gate — thin Python bridge around Reticulum (rnspure / RNS).

Called from Kotlin via Chaquopy. Identity and config live under the app-private
storage directory passed from Android (filesDir).

All Kotlin-facing entrypoints return a JSON string (json.dumps) so Chaquopy
does not have to map Python dicts — PyObject.get / Map casts are unreliable
for dict values (attribute/get method confusion).
"""

from __future__ import annotations

import json
import os
import threading
import time
import traceback
from typing import Any, Dict, Optional

_lock = threading.RLock()
_state: Dict[str, Any] = {
    "storage_dir": None,
    "config_dir": None,
    "identity_path": None,
    "running": False,
    "started_at": None,
    "host": None,
    "port": None,
    "display_name": "Operator",
    "identity_hash": None,
    "last_error": None,
    "announce_ok": False,
    "peer_estimate": 0,
}


_reticulum = None
_identity = None
_destination = None


def _dumps(payload: Dict[str, Any]) -> str:
    """Serialize for Kotlin: UTF-8 JSON string parsed with org.json.JSONObject."""
    return json.dumps(payload, ensure_ascii=False, separators=(",", ":"), default=str)


def _ok(**kwargs) -> str:
    out: Dict[str, Any] = {"ok": True, "error": None}
    out.update(kwargs)
    return _dumps(out)


def _err(msg: str, **kwargs) -> str:
    _state["last_error"] = msg
    out: Dict[str, Any] = {"ok": False, "error": msg}
    out.update(kwargs)
    return _dumps(out)


def _write_config(config_dir: str, host: str, port: int) -> None:
    os.makedirs(config_dir, exist_ok=True)
    os.makedirs(os.path.join(config_dir, "storage"), exist_ok=True)
    config_path = os.path.join(config_dir, "config")
    # Minimal config: transport on, no shared instance (Android IPC is unreliable),
    # single TCP Client pointing at the user-configured rnsd / TCP server.
    content = f"""# Generated by RNS Gate — do not commit secrets here.
[reticulum]
  enable_transport = Yes
  share_instance = No
  panic_on_interface_error = No

[logging]
  loglevel = 4

[interfaces]

  [[TCP Gateway]]
    type = TCPClientInterface
    enabled = Yes
    target_host = {host}
    target_port = {int(port)}
"""
    with open(config_path, "w", encoding="utf-8") as f:
        f.write(content)


def _reset_reticulum_singleton() -> None:
    """Allow a later start() in the same process after stop(). Best-effort."""
    try:
        import RNS

        RNS.Reticulum._Reticulum__instance = None  # type: ignore[attr-defined]
        RNS.Reticulum._Reticulum__exit_handler_ran = False  # type: ignore[attr-defined]
        RNS.Reticulum._Reticulum__interface_detach_ran = False  # type: ignore[attr-defined]
        if hasattr(RNS, "exit_called"):
            RNS.exit_called = False
    except Exception:
        pass


def _load_or_create_identity(path: str):
    import RNS

    os.makedirs(os.path.dirname(path), exist_ok=True)
    if os.path.isfile(path):
        identity = RNS.Identity.from_file(path)
        if identity is None:
            raise RuntimeError(f"Failed to load identity from {path}")
        return identity
    identity = RNS.Identity()
    if not identity.to_file(path):
        raise RuntimeError(f"Failed to save identity to {path}")
    return identity


def init_storage(storage_dir: str) -> str:
    """Prepare directories; does not start Reticulum. Returns JSON string."""
    with _lock:
        try:
            storage_dir = os.path.abspath(storage_dir)
            config_dir = os.path.join(storage_dir, "reticulum")
            identity_path = os.path.join(storage_dir, "identity")
            identity_parent = os.path.dirname(identity_path) or storage_dir
            for d in (storage_dir, config_dir, os.path.join(config_dir, "storage"), identity_parent):
                try:
                    os.makedirs(d, exist_ok=True)
                except OSError as oe:
                    return _err(f"init_storage failed: cannot create {d}: {oe}")
            # Sanity: dirs must be writable
            for d in (storage_dir, config_dir):
                if not os.path.isdir(d) or not os.access(d, os.W_OK):
                    return _err(f"init_storage failed: not writable: {d}")
            _state["storage_dir"] = storage_dir
            _state["config_dir"] = config_dir
            _state["identity_path"] = identity_path
            # Prefer HOME under app storage so RNS relative paths stay private.
            os.environ["HOME"] = storage_dir
            return _ok(
                storage_dir=storage_dir,
                config_dir=config_dir,
                identity_path=identity_path,
            )
        except OSError as e:
            return _err(f"init_storage failed: {e}")
        except Exception as e:
            return _err(f"init_storage failed: {e}")


def start(host: str, port: int, display_name: str = "Operator") -> str:
    """Write TCP config, start Reticulum, load identity, optional probe announce."""
    global _reticulum, _identity, _destination
    with _lock:
        try:
            if not _state["config_dir"] or not _state["identity_path"]:
                return _err("Call init_storage first")

            if _state["running"] and _reticulum is not None:
                # Already running — refresh status only.
                return status()

            host = (host or "").strip() or "127.0.0.1"
            port = int(port)
            display_name = (display_name or "Operator").strip() or "Operator"

            _write_config(_state["config_dir"], host, port)
            _reset_reticulum_singleton()

            import RNS

            def _log_cb(msg: str) -> None:
                # Android Logcat via Chaquopy stdout redirection also works;
                # keep a quiet callback sink if logdest is used.
                pass

            _reticulum = RNS.Reticulum(
                configdir=_state["config_dir"],
                loglevel=RNS.LOG_NOTICE,
            )
            _identity = _load_or_create_identity(_state["identity_path"])
            _destination = RNS.Destination(
                _identity,
                RNS.Destination.IN,
                RNS.Destination.SINGLE,
                "rnsgate",
                "node",
            )

            announce_ok = False
            try:
                app_data = display_name.encode("utf-8")[:128]
                _destination.announce(app_data=app_data)
                announce_ok = True
            except Exception as ae:
                _state["last_error"] = f"announce: {ae}"

            # Brief settle so TCP client can attempt connect.
            time.sleep(0.4)

            _state.update(
                {
                    "running": True,
                    "started_at": time.time(),
                    "host": host,
                    "port": port,
                    "display_name": display_name,
                    "identity_hash": _identity.hexhash,
                    "announce_ok": announce_ok,
                }
            )
            return status()
        except Exception as e:
            _reticulum = None
            _identity = None
            _destination = None
            _state["running"] = False
            tb = traceback.format_exc(limit=4)
            return _err(f"start failed: {e}", traceback=tb)


def stop() -> str:
    """Detach interfaces and clear running flag. Does not kill the Android process."""
    global _reticulum, _identity, _destination
    with _lock:
        try:
            if _state["running"]:
                try:
                    import RNS

                    RNS.Transport.detach_interfaces()
                except Exception as e:
                    _state["last_error"] = f"detach: {e}"
            _reticulum = None
            _identity = None
            _destination = None
            _state["running"] = False
            _state["started_at"] = None
            _state["announce_ok"] = False
            _reset_reticulum_singleton()
            return _ok(running=False)
        except Exception as e:
            return _err(f"stop failed: {e}")


def status() -> str:
    """Snapshot for Gate UI: identity, TCP up, rough peer/path counts."""
    with _lock:
        try:
            iface_up = False
            iface_detail = ""
            peer_estimate = 0
            path_count = 0

            if _state["running"]:
                try:
                    import RNS

                    for iface in list(getattr(RNS.Transport, "interfaces", []) or []):
                        name = getattr(iface, "name", "") or ""
                        online = bool(getattr(iface, "online", False) or getattr(iface, "is_connected", False))
                        # TCPClientInterface uses .online after connect
                        if "TCP" in name or getattr(iface, "initiator", False):
                            if online:
                                iface_up = True
                            detail_host = _state.get("host") or ""
                            detail_port = _state.get("port") or ""
                            iface_detail = f"{detail_host}:{detail_port}"
                            if not online:
                                # still show endpoint even if connecting
                                iface_detail = iface_detail + (" (connecting)" if detail_host else "")
                        elif online:
                            iface_up = iface_up or online

                    # Path table size as a rough "known destinations" count.
                    try:
                        path_count = len(getattr(RNS.Transport, "path_table", {}) or {})
                    except Exception:
                        path_count = 0
                    peer_estimate = path_count
                    _state["peer_estimate"] = peer_estimate
                except Exception as e:
                    _state["last_error"] = f"status: {e}"

            uptime_ms = 0
            if _state["running"] and _state["started_at"]:
                uptime_ms = int((time.time() - _state["started_at"]) * 1000)

            return _ok(
                running=_state["running"],
                identity_hash=_state.get("identity_hash"),
                display_name=_state.get("display_name"),
                host=_state.get("host"),
                port=_state.get("port"),
                interface_up=iface_up,
                interface_detail=iface_detail
                or (
                    f"{_state.get('host')}:{_state.get('port')}"
                    if _state.get("host")
                    else ""
                ),
                peer_estimate=peer_estimate,
                path_count=path_count,
                announce_ok=_state.get("announce_ok", False),
                uptime_ms=uptime_ms,
                last_error=_state.get("last_error"),
            )
        except Exception as e:
            return _err(f"status failed: {e}")


def regenerate_identity(display_name: Optional[str] = None) -> str:
    """Create a new identity file. Prefer calling while stopped."""
    global _identity, _destination
    with _lock:
        try:
            path = _state.get("identity_path")
            if not path:
                return _err("Call init_storage first")
            if _state["running"]:
                return _err("Disconnect before regenerating identity")
            import RNS

            if os.path.isfile(path):
                os.remove(path)
            identity = RNS.Identity()
            if not identity.to_file(path):
                return _err("Could not write new identity")
            _identity = identity
            _state["identity_hash"] = identity.hexhash
            if display_name:
                _state["display_name"] = display_name
            return _ok(identity_hash=identity.hexhash, display_name=_state["display_name"])
        except Exception as e:
            return _err(f"regenerate_identity failed: {e}")


def probe_announce(display_name: Optional[str] = None) -> str:
    """Send another announce if the node is running."""
    with _lock:
        try:
            if not _state["running"] or _destination is None:
                return _err("Not running")
            name = display_name or _state.get("display_name") or "Operator"
            _destination.announce(app_data=name.encode("utf-8")[:128])
            _state["announce_ok"] = True
            return _ok(announce_ok=True)
        except Exception as e:
            return _err(f"probe_announce failed: {e}")


def ping() -> str:
    """Lightweight health check used by Kotlin to verify Python/RNS import."""
    try:
        import RNS  # noqa: F401

        ver = getattr(RNS, "RNS_VERSION", None) or getattr(RNS, "__version__", "unknown")
        return _ok(rns_version=str(ver), module="rns_bridge")
    except Exception as e:
        return _err(f"RNS import failed: {e}")
